# Generated by Django 5.0.6 on 2024-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название фильма')),
                ('description', models.CharField(max_length=240, verbose_name='Описание фильма')),
                ('content', models.TextField(verbose_name='Содержание фильма')),
                ('review', models.CharField(max_length=240, verbose_name='Отзыв')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
